<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CHDTIFA" failures="3" tests="20" name="uAT_APIs.Booking_Controller_APIs" time="133.787" errors="0" timestamp="2025-03-19T11:39:31 IST" skipped="0">
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="UserLoginData" time="0.663"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="UpdateVehicleStatus" time="0.407"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="UpdateCustomerTAG" time="0.496"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="Update_CustomerExpected_Date" time="0.409"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getSubTabs" time="0.387"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getReceiptDetails" time="0.349"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getLoanStatus" time="0.606">
    <failure message="Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at uAT_APIs.Booking_Controller_APIs.StatusCode(Booking_Controller_APIs.java:517)
at uAT_APIs.Booking_Controller_APIs.getLoanStatus(Booking_Controller_APIs.java:193)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getLoanStatus -->
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getDocumentList" time="0.351"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getCustomerSVOC" time="0.361"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getBookingsColumnWise" time="0.675"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getBookingList" time="0.611"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="downloadBookingList" time="61.536"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="EmployeeDataByMspin" time="1.019"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getCustomerTAGList" time="0.509"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getCustomerTAG_BookingIdv" time="0.372"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getColumnNames" time="0.367"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getAccesssoriesDetails" time="1.399"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="Booking_Details_BookingIdv" time="1.839"/>
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getDocument" time="30.716">
    <failure message="Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at uAT_APIs.Booking_Controller_APIs.StatusCode(Booking_Controller_APIs.java:517)
at uAT_APIs.Booking_Controller_APIs.getDocument(Booking_Controller_APIs.java:483)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getDocument -->
  <system-out/>
  <testcase classname="uAT_APIs.Booking_Controller_APIs" name="getManualDocket" time="30.715">
    <failure message="Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at uAT_APIs.Booking_Controller_APIs.StatusCode(Booking_Controller_APIs.java:517)
at uAT_APIs.Booking_Controller_APIs.getManualDocket(Booking_Controller_APIs.java:508)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getManualDocket -->
  <system-out/>
</testsuite> <!-- uAT_APIs.Booking_Controller_APIs -->
